version: '3'

services:
  tododDB:
    image: postgres:15.3
    container_name: todos-tododDB
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data